/**
 * The one entry point for MCP, the CLI, and the VS Code extension: the
 * review pipeline (`executeReview`), the engine modules it runs, and the
 * public surface of `@debuggatha/core` those adapters need.
 */

export type {
  AcceptedDeviationItem,
  BuildRepositoryContextOptions,
  Capability,
  CapabilityConfidence,
  CapabilityKind,
  CapabilityOrigin,
  CapabilityRegistry,
  Category,
  Confidence,
  ConflictRecord,
  ConventionItem,
  CreateFindingInput,
  CreateMemoryItemInput,
  CriteriaProfile,
  CriteriaRule,
  DecisionItem,
  DependencyProfile,
  DocumentationProfile,
  Evidence as RepositoryEvidence,
  Evidence,
  ExceptionItem,
  ExceptionKind,
  FilterFindingsResult,
  Finding,
  FindingFingerprint,
  FindingLifecycleStatus,
  FindingLocation,
  FindingMatcher,
  HistoryEvent,
  KnowledgeEntry,
  Ledger,
  LedgerEntry,
  LedgerEntryFilter,
  LedgerSummary,
  MatchOutcome,
  MemoryCategory,
  MemoryConfidence,
  MemoryEvidence,
  MemoryHistoryEvent,
  MemoryItem,
  MemoryLifecycleStatus,
  MemoryOrigin,
  MemoryStore,
  PackDependency,
  PolicyRule,
  PolicyRuleOrigin,
  Recommendation,
  RecommendationEdit,
  RecommendationExample,
  RepositoryContext,
  RepositoryContextCache,
  RepositorySnapshotRef,
  ReviewAssociation,
  ReviewDepth,
  ReviewHistoryNoteItem,
  ReviewLifecycleStatus,
  ReviewPack,
  ReviewPackKind,
  ReviewPackReference,
  ReviewPolicy,
  ReviewPolicyReference,
  ReviewRequest,
  ReviewResult,
  ReviewScope,
  ReviewSession,
  ReviewSource,
  ReviewSummary,
  Rule,
  RuleScope,
  Severity,
  SkillContext,
  SkillDescriptor,
  SkillTier,
  StackProfile,
  StackSignal,
  SuppressedFinding,
  SuppressionItem,
  SyncReport,
  SyncScope,
  TransitionOrigin,
  UnderstandingProfile,
} from "@debuggatha/core";
export {
  acceptedDeviationMatches,
  activateMemory,
  addMemoryItem,
  archiveMemory,
  assembleContext,
  associationFor,
  buildRepositoryContext,
  CATEGORIES,
  CURRENT_SCHEMA_VERSION,
  canTransition,
  canTransitionFinding,
  canTransitionMemory,
  computeFindingFingerprint,
  confirmMemory,
  createEmptyLedger,
  createEmptyMemoryStore,
  createFinding,
  createInMemoryCache,
  createInMemoryRegistry,
  createLedgerEntry,
  createMemoryItem,
  createReviewRequest,
  createReviewResult,
  createReviewSession,
  defaultFindingMatcher,
  deprecateMemory,
  deriveCapabilities,
  deserializeLedger,
  exceptionMatches,
  FINDING_LIFECYCLE_STATUSES,
  filterSuppressedFindings,
  getEntry,
  getHistory,
  isActiveFindingStatus,
  isActiveMemoryStatus,
  isTerminal,
  ledgerFilePath,
  listEntries,
  loadLedger,
  loadMemoryStore,
  MEMORY_LIFECYCLE_STATUSES,
  REVIEW_DEPTHS,
  REVIEW_LIFECYCLE_STATUSES,
  reactivateMemory,
  refreshLedgerEntry,
  rejectMemory,
  removeMemoryItem,
  resolvePolicy,
  ruleIdFromEvidence,
  SKILL_TIERS,
  saveLedger,
  saveMemoryStore,
  serializeLedger,
  snapshotRefFor,
  suggestMemory,
  summarizeCapabilities,
  summarizeFindings,
  summarizeLedger,
  suppressionMatches,
  synchronizeReviewResult,
  transitionFinding,
  transitionMemory,
  transitionSession,
  updateFindingStatus,
  validateReviewPack,
} from "@debuggatha/core";
export type {
  AnalysisCache,
  AnalysisCacheEntry,
  AnalysisFingerprint,
  AnalysisResult,
  ChangeImpact,
  DeadCodeFinding,
  DeadCodeKind,
  DependencyCycle,
  DependencyEdge,
  DependencyGraph,
  LayerModel,
  LayerName,
  LayerViolation,
  ModuleBoundary,
  ModuleKind,
  OwnershipSignal,
  OwnershipSource,
  PublicApiSurface,
  PublicApiSymbol,
  RunAnalysisOptions,
} from "./analysis-engine/index.js";
export {
  buildAnalysisFingerprint,
  buildDependencyGraph,
  buildLayerModel,
  buildPublicApiSurface,
  createInMemoryAnalysisCache,
  detectCycles,
  detectDeadCode,
  detectLayerViolations,
  detectOwnership,
  estimateChangeImpact,
  fingerprintChanged,
  inferModuleBoundaries,
  LAYER_ORDER,
  runAnalysis,
} from "./analysis-engine/index.js";
export type {
  AnalyzerAdapter,
  AnalyzerFinding,
  AnalyzerInventoryEntry,
  AnalyzerOptions,
  AnalyzerRun,
  AnalyzerStatus,
  AnalyzerTrust,
} from "./analyzers/index.js";
export { ADAPTERS, inventoryAnalyzers } from "./analyzers/index.js";
export type { Baseline, BaselineEntry } from "./baseline.js";
export { BASELINE_FILE, clearBaseline, loadBaseline } from "./baseline.js";
export type { ChangedFiles } from "./infrastructure/index.js";
export { LocalGitProvider, listChangedFiles } from "./infrastructure/index.js";
export type {
  FindingRef,
  ReviewChanges,
  ReviewPipelineInput,
  ReviewPipelineOutput,
  ReviewPipelineScope,
} from "./pipeline.js";
export {
  createBaseline,
  executeReview,
  resolveRequestedPackIds,
  toRepoRelative,
} from "./pipeline.js";
export { assemblePolicy, defaultCapabilityRegistry } from "./policies/index.js";
export type { RepositoryProvider } from "./provider.js";
export { isIgnoredPath } from "./scan-scope/index.js";
export type {
  CompletionRequest,
  LocalProviderName,
  LocalProviderOptions,
  SemanticOptions,
  SemanticProvider,
  SemanticReviewOutput,
  SemanticRun,
} from "./semantic/index.js";
export {
  assertLoopback,
  createLocalProvider,
  executeReviewWithSemantics,
  LOCAL_PROVIDERS,
  refineFindings,
} from "./semantic/index.js";
export { addedLinesByFile } from "./skills/engine/diff-parser.js";
export type { Guidance } from "./skills/engine/guidance.js";
export { guidanceFor } from "./skills/engine/guidance.js";
export type { InlineSuppression } from "./skills/engine/suppress.js";
export { inlineSuppressionComment } from "./skills/engine/suppress.js";
export {
  reviewArchitecture,
  reviewDiff,
  reviewFiles,
} from "./skills/index.js";
