import { afterEach, describe, expect, it } from "bun:test";
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import type { Finding } from "./index.js";
import { createBaseline, executeReview } from "./pipeline.js";

/**
 * Regression tests for review trust: what Debuggatha refuses to look at, what it refuses to
 * call a finding, and how a person tells it to be quiet. The fixtures reproduce what real
 * repositories produced: dependency directories, minified bundles, build output, Kotlin
 * constants named like secrets, and fake credentials in tests.
 */

let dirs: string[] = [];
afterEach(() => {
  for (const dir of dirs) rmSync(dir, { recursive: true, force: true });
  dirs = [];
});

function makeRepo(files: Record<string, string>, options: { git?: boolean } = {}): string {
  const root = mkdtempSync(join(tmpdir(), "debuggatha-trust-"));
  dirs.push(root);
  for (const [path, content] of Object.entries(files)) {
    const full = join(root, path);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, content);
  }
  if (options.git) execFileSync("git", ["init", "-q"], { cwd: root });
  return root;
}

function review(root: string, extra: Partial<Parameters<typeof executeReview>[0]> = {}) {
  return executeReview({
    rootDir: root,
    scope: { kind: "workspace" },
    depth: "full",
    packIds: [],
    policyId: undefined,
    sourceName: "test",
    persist: false,
    ...extra,
  });
}

const filesOf = (output: ReturnType<typeof review>) =>
  [...new Set(output.result.findings.map((f) => f.locations[0]?.file))].sort();
const ruleOf = (finding: Finding): string | undefined => {
  for (const evidence of finding.evidence) if ("ruleId" in evidence) return evidence.ruleId;
  return undefined;
};

const PKG = JSON.stringify({ name: "fixture", devDependencies: { typescript: "^5" } });
const BAD = "var legacy = 1;\nif (legacy == 2) { eval(input); }\n";

describe("scope: only code the project owns is reviewed", () => {
  it("skips dependency, build-output, generated, and minified code", () => {
    const minified = `!function(e){var a=${"x".repeat(3000)};}(window);`;
    const root = makeRepo({
      "package.json": PKG,
      "src/app.ts": BAD,
      "vendor/lib/util.js": BAD,
      "node_modules/pkg/index.js": BAD,
      "dist/bundle.js": BAD,
      "build/out.js": BAD,
      "public/prism.js": minified,
      "src/api.generated.ts": BAD,
      "src/proto.ts": `// Code generated by protoc. DO NOT EDIT.\n${BAD}`,
      "types/index.d.ts": "export type A = any;\n",
    });
    expect(filesOf(review(root))).toEqual(["src/app.ts"]);
  });

  it("lets the repository's own .gitignore decide", () => {
    const root = makeRepo(
      {
        "package.json": PKG,
        ".gitignore": "scratch/\nlocal-*.ts\n",
        "src/app.ts": BAD,
        "scratch/try.ts": BAD,
        "src/local-notes.ts": BAD,
      },
      { git: true },
    );
    expect(filesOf(review(root))).toEqual(["src/app.ts"]);
  });

  it("treats bin/ as build output only beside a build tool", () => {
    const withGradle = makeRepo({
      "build.gradle.kts": "// build",
      "server/src/App.kt": "fun main() {}\n",
      "server/bin/test/Copy.kt": 'val password = "hunter22222"\n',
    });
    expect(filesOf(review(withGradle))).toEqual([]);

    const nodeCli = makeRepo({ "package.json": PKG, "bin/run.js": BAD });
    expect(filesOf(review(nodeCli))).toEqual(["bin/run.js"]);
  });

  it("does not review generated paths that a diff touches", () => {
    const root = makeRepo({ "package.json": PKG });
    const diff = [
      "diff --git a/vendor/x.js b/vendor/x.js",
      "--- a/vendor/x.js",
      "+++ b/vendor/x.js",
      "@@ -0,0 +1 @@",
      "+eval(payload);",
      "diff --git a/src/y.js b/src/y.js",
      "--- a/src/y.js",
      "+++ b/src/y.js",
      "@@ -0,0 +1 @@",
      "+eval(payload);",
      "",
    ].join("\n");
    const output = review(root, { scope: { kind: "diff", base: undefined, diff } });
    expect(filesOf(output)).toEqual(["src/y.js"]);
  });
});

describe("precision: what used to be called critical and was not", () => {
  it("raises nothing for Kotlin constants named like secrets, or fake credentials in tests", () => {
    const root = makeRepo({
      "build.gradle.kts": "// build",
      "core/src/main/kotlin/OfflineCredentialStore.kt": [
        'private const val KEY_ACCESS_TOKEN = "offline_access_token"',
        'private const val KEY_REFRESH_TOKEN = "offline_refresh_token"',
        'private const val PREFS_NAME = "secure_prefs"',
      ].join("\n"),
      "server/src/test/kotlin/AuthTest.kt": 'val password = "test_password"\n',
    });
    const output = review(root);
    expect(output.result.findings).toEqual([]);
  });

  it("does not call an idiom or text a finding", () => {
    const root = makeRepo({
      "package.json": PKG,
      "src/a.ts": [
        "export const f = (val: string | null) => {",
        "  if (val == null) return null;",
        '  const doc = "never call eval(x) or use == here";',
        "  // var old = eval(x);",
        "  return val;",
        "};",
      ].join("\n"),
    });
    expect(review(root).result.findings).toEqual([]);
  });

  it("no longer ranks loose equality with code injection", () => {
    const root = makeRepo({ "package.json": PKG, "src/a.ts": BAD });
    const severities = Object.fromEntries(
      review(root).result.findings.map((f) => [ruleOf(f), f.severity]),
    );
    expect(severities["no-eval"]).toBe("high");
    expect(severities.eqeqeq).toBe("medium");
    expect(severities["no-var"]).toBe("low");
    expect(Object.values(severities)).not.toContain("critical");
  });

  it("still catches a real credential, as critical, and never writes it to disk", () => {
    const secret = "sk_live_1234567890abcdef";
    const root = makeRepo({ "package.json": PKG, "src/pay.ts": `const key = "${secret}";\n` });
    const output = review(root, { persist: true });
    const [finding] = output.result.findings.filter((f) => ruleOf(f) === "no-hardcoded-secrets");
    expect(finding?.severity).toBe("critical");
    expect(finding?.confidence).toBe("high");
    const ledger = readFileSync(join(root, ".debuggatha", "ledger.json"), "utf8");
    expect(ledger).not.toContain(secret);
  });
});

describe("findings tell you what to do", () => {
  it("carries the column, why it matters, and the same code before and after", () => {
    const root = makeRepo({ "package.json": PKG, "src/a.ts": "  var count = 0;\n" });
    const [finding] = review(root).result.findings;
    expect(finding?.locations[0]?.columns).toEqual({ start: 3, end: 8 });
    expect(finding?.confidence).toBe("high");
    expect(finding?.explanation).toContain("hoisted");
    const recommendation = finding?.recommendations[0];
    expect(recommendation?.summary).toContain("const");
    expect(recommendation?.example).toEqual({ before: "var total = 0;", after: "let total = 0;" });
  });

  it("names the file relative to the repository in every recommendation", () => {
    const root = makeRepo({ "package.json": PKG, "src/a.ts": "var x = 1;\n" });
    const output = review(root, { scope: { kind: "files", paths: [join(root, "src", "a.ts")] } });
    for (const finding of output.result.findings) {
      for (const recommendation of finding.recommendations) {
        expect(recommendation.targetFile).toBe("src/a.ts");
        expect(recommendation.id).not.toContain(root);
      }
    }
  });
});

describe("inline suppression", () => {
  it("hides a finding the code says it accepts, and reports what it hid and why", () => {
    const root = makeRepo({
      "package.json": PKG,
      "src/a.ts": [
        "run(eval(input)); // debuggatha-ignore no-eval -- sandboxed plugin loader",
        "// debuggatha-ignore-next-line no-var -- legacy shim",
        "var shim = 1;",
        "var other = 2;",
      ].join("\n"),
    });
    const output = review(root);
    expect(output.result.findings.map(ruleOf)).toEqual(["no-var"]);
    expect(output.result.findings[0]?.locations[0]?.lines?.start).toBe(4);
    expect(output.suppressedInline).toEqual([
      { file: "src/a.ts", line: 1, ruleId: "no-eval", reason: "sandboxed plugin loader" },
      { file: "src/a.ts", line: 3, ruleId: "no-var", reason: "legacy shim" },
    ]);
  });
});

describe("adoption mode: a baseline reports only what is new", () => {
  it("accepts what exists, reports what is added, and keeps tracking everything", () => {
    const root = makeRepo({ "package.json": PKG, "src/a.ts": BAD });
    const before = review(root).result.findings.length;
    expect(before).toBeGreaterThan(0);

    const { count } = createBaseline({ rootDir: root, sourceName: "test" });
    expect(count).toBe(before);

    const quiet = review(root, { persist: true });
    expect(quiet.result.findings).toEqual([]);
    expect(quiet.baselined).toBe(before);

    writeFileSync(join(root, "src", "b.ts"), "var fresh = 1;\n");
    const later = review(root, { persist: true });
    expect(later.result.findings.map((f) => f.locations[0]?.file)).toEqual(["src/b.ts"]);
    expect(later.baselined).toBe(before);

    const ledger = JSON.parse(readFileSync(join(root, ".debuggatha", "ledger.json"), "utf8"));
    expect(ledger.entries.length).toBe(before + 1);
  });

  it("does not resurface an accepted finding when unrelated edits move it", () => {
    const root = makeRepo({ "package.json": PKG, "src/a.ts": BAD });
    createBaseline({ rootDir: root, sourceName: "test" });
    writeFileSync(join(root, "src", "a.ts"), `// header\n// more\n\n${BAD}`);
    expect(review(root).result.findings).toEqual([]);
  });

  it("can show everything, baselined or not", () => {
    const root = makeRepo({ "package.json": PKG, "src/a.ts": BAD });
    const total = review(root).result.findings.length;
    createBaseline({ rootDir: root, sourceName: "test" });
    const all = review(root, { includeBaselined: true });
    expect(all.result.findings.length).toBe(total);
    expect(all.baselined).toBe(0);
  });

  it("stops accepting a finding once the code it was about is gone and comes back", () => {
    const root = makeRepo({ "package.json": PKG, "src/a.ts": "var once = 1;\n" });
    createBaseline({ rootDir: root, sourceName: "test" });
    writeFileSync(join(root, "src", "a.ts"), "var once = 1;\nvar twice = 2;\n");
    expect(review(root).result.findings.map((f) => f.locations[0]?.lines?.start)).toEqual([2]);
  });

  it("rejects a corrupt baseline instead of silently reporting nothing", () => {
    const root = makeRepo({
      "package.json": PKG,
      "src/a.ts": BAD,
      ".debuggatha/baseline.json": "{not json",
    });
    expect(() => review(root)).toThrow("baseline.json");
  });
});
