/**
 * `@debuggatha/core` is the stable façade MCP, the CLI, and the VS Code
 * panel depend on — see the root README's package graph. It re-exports
 * each epic's package as it lands: Repository Intelligence (Epic 1), the
 * Review Engine domain (Epic 2), the Knowledge System (Epic 3), the
 * Findings Ledger (Epic 4), plus the thin `@debuggatha/policies` wiring
 * and `@debuggatha/skills`' Review Skill functions — so Epic 5's MCP
 * package can depend on this one façade instead of five separate domain
 * packages. This is exports only; the multi-step orchestration (build a
 * RepositoryContext, assemble a policy, run a Skill, sync the result into
 * a Ledger) is composed by whatever calls these functions — today that's
 * `@debuggatha/mcp`'s tool handlers, not this package. Epic 12 adds
 * `@debuggatha/analysis-engine`'s deterministic repository analysis
 * pipeline to this façade the same way.
 */

export type {
  AnalysisCache,
  AnalysisCacheEntry,
  AnalysisFingerprint,
  AnalysisResult,
  ChangeImpact,
  DeadCodeFinding,
  DeadCodeKind,
  DependencyCycle,
  DependencyEdge,
  DependencyGraph,
  LayerModel,
  LayerName,
  LayerViolation,
  ModuleBoundary,
  ModuleKind,
  OwnershipSignal,
  OwnershipSource,
  PublicApiSurface,
  PublicApiSymbol,
  RunAnalysisOptions,
} from "@debuggatha/analysis-engine";
export {
  buildAnalysisFingerprint,
  buildDependencyGraph,
  buildLayerModel,
  buildPublicApiSurface,
  createInMemoryAnalysisCache,
  detectCycles,
  detectDeadCode,
  detectLayerViolations,
  detectOwnership,
  estimateChangeImpact,
  fingerprintChanged,
  inferModuleBoundaries,
  LAYER_ORDER,
  runAnalysis,
} from "@debuggatha/analysis-engine";
export type {
  BuildContextIntelligenceOptions,
  CapabilityContextItem,
  ContextCategory,
  ContextConfidence,
  ContextEvidence,
  ContextFingerprint,
  ContextIntelligenceCache,
  ContextIntelligenceCacheEntry,
  ContextIntelligenceResult,
  ContextItem,
  DocumentationContextItem,
  EngineeringConventionItem,
  GitContextItem,
  GitContextKey,
  OwnershipContextItem,
  ProjectMetadataItem,
  WorkflowContextItem,
  WorkflowKind,
} from "@debuggatha/context-intelligence";
export {
  buildCapabilityItems as buildContextCapabilityItems,
  buildContextFingerprint,
  buildContextIntelligence,
  buildConventionItems,
  buildDocumentationItems as buildDocumentationContextItems,
  buildGitContextItems,
  buildOwnershipItems as buildOwnershipContextItems,
  buildProjectMetadataItems,
  conventionsToPolicyStatements,
  createInMemoryContextCache,
  detectWorkflow,
  hasContextFingerprintChanged,
} from "@debuggatha/context-intelligence";
export type {
  FindingFingerprint,
  FindingLifecycleStatus,
  FindingMatcher,
  HistoryEvent,
  Ledger,
  LedgerEntry,
  LedgerEntryFilter,
  LedgerSummary,
  MatchOutcome,
  RepositorySnapshotRef,
  ReviewAssociation,
  SyncReport,
  SyncScope,
  TransitionOrigin,
} from "@debuggatha/findings-ledger";
export {
  associationFor,
  CURRENT_SCHEMA_VERSION,
  canTransitionFinding,
  computeFindingFingerprint,
  createEmptyLedger,
  createLedgerEntry,
  defaultFindingMatcher,
  deserializeLedger,
  FINDING_LIFECYCLE_STATUSES,
  getEntry,
  getHistory,
  isActiveFindingStatus,
  ledgerFilePath,
  listEntries,
  loadLedger,
  refreshLedgerEntry,
  saveLedger,
  serializeLedger,
  snapshotRefFor,
  summarizeLedger,
  synchronizeReviewResult,
  transitionFinding,
  updateFindingStatus,
} from "@debuggatha/findings-ledger";
export type {
  CapabilityRegistry,
  ConflictRecord,
  KnowledgeEntry,
  PackDependency,
  PolicyRule,
  PolicyRuleOrigin,
  ReviewPack,
  ReviewPackKind,
  ReviewPolicy,
  Rule,
  RuleScope,
  SkillContext,
  SkillDescriptor,
  SkillTier,
} from "@debuggatha/knowledge-system";
export {
  assembleContext,
  createInMemoryRegistry,
  resolvePolicy,
  SKILL_TIERS,
  validateReviewPack,
} from "@debuggatha/knowledge-system";
export { assemblePolicy, defaultCapabilityRegistry } from "@debuggatha/policies";
export type {
  BuildRepositoryContextOptions,
  Capability,
  CapabilityConfidence,
  CapabilityKind,
  CapabilityOrigin,
  CriteriaProfile,
  CriteriaRule,
  DependencyProfile,
  DocumentationProfile,
  Evidence as RepositoryEvidence,
  RepositoryContext,
  RepositoryContextCache,
  StackProfile,
  StackSignal,
  UnderstandingProfile,
} from "@debuggatha/repository-intelligence";
export {
  buildRepositoryContext,
  createInMemoryCache,
  deriveCapabilities,
  summarizeCapabilities,
} from "@debuggatha/repository-intelligence";
export type {
  AcceptedDeviationItem,
  ConventionItem,
  CreateMemoryItemInput,
  DecisionItem,
  ExceptionItem,
  ExceptionKind,
  FilterFindingsResult,
  MemoryCategory,
  MemoryConfidence,
  MemoryEvidence,
  MemoryHistoryEvent,
  MemoryItem,
  MemoryLifecycleStatus,
  MemoryOrigin,
  MemoryStore,
  ReviewHistoryNoteItem,
  SuppressedFinding,
  SuppressionItem,
} from "@debuggatha/repository-memory";
export {
  acceptedDeviationMatches,
  activateMemory,
  addMemoryItem,
  archiveMemory,
  canTransitionMemory,
  confirmMemory,
  createEmptyMemoryStore,
  createMemoryItem,
  deprecateMemory,
  exceptionMatches,
  filterSuppressedFindings,
  isActiveMemoryStatus,
  loadMemoryStore,
  MEMORY_LIFECYCLE_STATUSES,
  reactivateMemory,
  rejectMemory,
  removeMemoryItem,
  saveMemoryStore,
  suggestMemory,
  suppressionMatches,
  transitionMemory,
} from "@debuggatha/repository-memory";
export type {
  Category,
  Confidence,
  CreateFindingInput,
  Evidence,
  Finding,
  FindingLocation,
  Recommendation,
  ReviewDepth,
  ReviewLifecycleStatus,
  ReviewPackReference,
  ReviewPolicyReference,
  ReviewRequest,
  ReviewResult,
  ReviewScope,
  ReviewSession,
  ReviewSource,
  ReviewSummary,
  Severity,
} from "@debuggatha/review-engine";
export {
  CATEGORIES,
  canTransition,
  createFinding,
  createReviewRequest,
  createReviewResult,
  createReviewSession,
  isTerminal,
  REVIEW_DEPTHS,
  REVIEW_LIFECYCLE_STATUSES,
  summarizeFindings,
  transitionSession,
} from "@debuggatha/review-engine";
export type {
  ContextBudget,
  HealthStatus,
  ModelInfo,
  PromptBudgetResult,
  Provider,
  ProviderRegistry,
  ResolvedRuntime,
  RunSemanticReviewInput,
  RunSemanticReviewOutput,
  RuntimeEngine,
  RuntimeExecutionMetadata,
  RuntimeSelection,
  SemanticConfidence,
  SemanticEvidence,
  SemanticExecutionRequest,
  SemanticFindingCandidate,
  SemanticReviewResult,
  SemanticSourceUnit,
  SemanticStreamEvent,
  StreamSemanticReviewOutput,
} from "@debuggatha/runtime-engine";
export {
  budgetSourceUnits,
  chunkSourceUnit,
  consumeToCompletion,
  createLMStudioProvider,
  createOllamaProvider,
  createProviderRegistry,
  createRuntimeEngine,
  estimateTokens,
  parseSemanticResponse,
  RuntimeSelectionError,
} from "@debuggatha/runtime-engine";
export {
  reviewArchitecture,
  reviewDiff,
  reviewFiles,
  runSemanticFindings,
} from "@debuggatha/skills";
export type {
  ReviewPipelineInput,
  ReviewPipelineOutput,
  ReviewPipelineScope,
} from "./pipeline.js";
export { executeReview } from "./pipeline.js";
export type { RepositoryProvider } from "./provider.js";
